# Generated by Django 5.1.6 on 2025-03-07 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_rename_description_transaction_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
    ]
